image: registry.webstollen.com:443/docker/jtl-plugin-ci:master

stages:
  - test
  - build
  - finalize
  - publish

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml


composer:
  stage: build
  only:
    - tags
    - master
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor
    policy: pull
  script:
    - composer install --no-dev -o
  artifacts:
    expire_in: 3 days
    untracked: true

pack:
  stage: finalize
  only:
    - tags
    - master
  script:
    - rm -rf .gitlab-ci.yml .git/
    - cd ..
    - compiler $CI_PROJECT_DIR $CI_PROJECT_DIR
    - zip -r $CI_PROJECT_DIR/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip $CI_PROJECT_NAME
  artifacts:
    expire_in: 30 days
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip

upload:
  stage: publish
  only:
    - tags
    - master
  script:
    - aws configure set region eu-central-1
    - aws s3 cp $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip s3://$S3_BUCKET/jtl-plugins/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip